title = "ロックスター・エナジードリンク"
baseURL = "https://higgma.github.io/rockstar/"
languageCode = "ja-jp"
theme = "kiss"

# github pages
publishDir = "docs"

# for summary
hasCJKLanguage = true
summaryLength = 140
