title = "ロックスター・エナジードリンク"
baseURL = "https://higgma.github.io/rockstar/"
languageCode = "ja-jp"

# github pages
publishDir = "docs"

# for summary
hasCJKLanguage = true
summaryLength = 140

# tmaiaroto/hugo-redlounge
theme = "redlounge"
[params]
    sidebartitle = "Rockstar"
    sidebartagline = "Is super awesome"
