version: 2.1
jobs:
  build:
    docker:
      - image: golang:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: go get -v github.com/gohugoio/hugo
      - run: hugo
      - run: |
          git config --global user.name CircleCI
          git config --global user.email "<>"
          git add -A
          git commit -m "[ci skip] Circle CI"
      - run: git push origin master
