version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
      working_directory: ~/repo
      steps:
        - checkout
        - run: >
          git submodule sync
          git submodule update --init
          go get github.com/gohugoio/hugo
          hugo
        - run: >
          git config --global user.name CircleCI
          git config --global user.email "<>"
          git add -A
          git commit -m "[ci skip] Circle CI"
        - run: >
          git push origin master
