version: 2.1
jobs:
  build:
    docker:
      - image: golang:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: go get -v github.com/gohugoio/hugo
      - run: hugo
      - run: |
          git config --global user.name CircleCI
          git config --global user.email "<>"
          git add -A

          if [ "$(git diff --cached --numstat | wc -l)" -ne "0" ]; then
            git commit -m "[ci skip] Circle CI"
            git push origin master
          else
            echo "nothing to commit."
          fi
